### ISSUE TITLE
Ayah sign in Kufi

### ISSUE THREAD

**Issue by khaledhosny** [asibahi/nun#1]
The _ayah_ signs in _Kufi_ should have no spaces around them (i.e. it looks like the text was written first then ayah signs were drawn in the space between the letters).

Furthermore, when they happens at the end of the line they should go completely in the margin.

**Comment by asibahi** [comment]
You mean like this right? 

![ikhlas_50](https://github.com/asibahi/nun/assets/17417266/399e2f43-bc3b-4546-97f8-16b0d1a1e55d)

I tampered with the shaping output to get it done with hard coded glyph values (just the simple one for now).

```rust
pub fn shape_line(hb_font: &mut hb::Font<'_>, line: &str) -> Vec<Glyph> {
    const END_OF_AYAH: u32 = 357;
    const SPACE: u32 = 1;

    let buffer = hb::UnicodeBuffer::new().add_str(line);
    let output = hb::shape(hb_font, buffer, &[]);

    let mut ret = vec![];

    for (info, pos) in output.get_glyph_infos().iter().zip(output.get_glyph_positions()) {
        let prev = ret.last();
        let g = Glyph {
            codepoint: info.codepoint,
            cluster: info.cluster,
            x_advance: {
                if info.codepoint == END_OF_AYAH
                    || (info.codepoint == SPACE
                        && prev.is_some_and(|p: &Glyph| p.codepoint == END_OF_AYAH))
                {
                    0
                } else {
                    pos.x_advance
                }
            },
            x_offset: if info.codepoint == END_OF_AYAH { -pos.x_advance } else { pos.x_offset },
            y_advance: pos.y_advance,
            y_offset: pos.y_offset,
        };

        ret.push(g);
    }

    ret
}
```

However, doing this would make the program font-specific. And honestly I prefer the look of the previous output.

This can be added to the Font via the WASM shaper, with very similar code, if I understand that feature correctly.

**Comment by khaledhosny** [comment]
For the margins, the font has [`lfbd`](https://learn.microsoft.com/en-us/typography/opentype/spec/features_ko#lfbd) (Left Bounds) and [`rtbd`](https://learn.microsoft.com/en-us/typography/opentype/spec/features_pt#rtbd) (Right Bounds) features, if you apply them to the ayah mark when it comes at the end of the line (or start of the line, which is rare, but sometimes happens), it should make it zero width, so it protrudes at the margin. (HarfBuzz has API to query these features, [`hb_ot_layout_lookup_get_optical_bound()`](https://harfbuzz.github.io/harfbuzz-hb-ot-layout.html#hb-ot-layout-lookup-get-optical-bound), if you want to take that into account when calculating line break badness)

For inside the line ayah, this can be achieved by modifying the input text to drop the spaces around of the ayah mark. This would loose the line break opportunity, so ZWSP (U+200B) can be used instead.

**Comment by khaledhosny** [comment]
(BTW, in كفوًا, the _tanween_ should be on the _alef_ for _kufi_ styles, so it should be كفواً).

**Comment by khaledhosny** [comment]
Also, to identify what character a glyph belongs on, you use info.cluster, it is an index into input string (it is a bit tricky to use, though, because of combining marks, decomposition, ligature, check HarfBuzz user manual on how to use it).

**Comment by asibahi** [comment]
> For the margins, the font has [`lfbd`](https://learn.microsoft.com/en-us/typography/opentype/spec/features_ko#lfbd) (Left Bounds) and [`rtbd`](https://learn.microsoft.com/en-us/typography/opentype/spec/features_pt#rtbd) (Right Bounds) features, if you apply them to the _ayah_ mark when it comes at the end of the line (or start of the line, which is rare, but sometimes happens), it should make it zero width, so it protrudes at the margin. (HarfBuzz has API to query these features, [`hb_ot_layout_lookup_get_optical_bound()`](https://harfbuzz.github.io/harfbuzz-hb-ot-layout.html#hb-ot-layout-lookup-get-optical-bound), if you want to take that into account when calculating line break badness)

Querying the font with FontGoggles , the features seem to be doing the same what I am in that code sample above when it is at the end of line. I have been trying to avoid mutating the input string (as that would require a lot of either copying or pointer bookkeeping).

> Also, to identify what character a glyph belongs on, you use info.cluster, it is an index into input string (it is a bit tricky to use, though, because of combining marks, decomposition, ligature, check HarfBuzz user manual on how to use it).

Yeah I understand the cluster marker. I am not sure what this is in reference to.

I worked on it a bit yesterday and managed to make it work for the other end of ayah markers.

![ikhlas_50](https://github.com/asibahi/nun/assets/17417266/dc63f623-b22d-4cc1-974b-c264065bf540)

I am going to try adding this to the font via the wasm shaper. I don't know how to make it feature gated tho. (and which feature? ss02?)

**Comment by khaledhosny** [comment]
> > For the margins, the font has [`lfbd`](https://learn.microsoft.com/en-us/typography/opentype/spec/features_ko#lfbd) (Left Bounds) and [`rtbd`](https://learn.microsoft.com/en-us/typography/opentype/spec/features_pt#rtbd) (Right Bounds) features, if you apply them to the _ayah_ mark when it comes at the end of the line (or start of the line, which is rare, but sometimes happens), it should make it zero width, so it protrudes at the margin. (HarfBuzz has API to query these features, [`hb_ot_layout_lookup_get_optical_bound()`](https://harfbuzz.github.io/harfbuzz-hb-ot-layout.html#hb-ot-layout-lookup-get-optical-bound), if you want to take that into account when calculating line break badness)
> 
> Querying the font with FontGoggles , the features seem to be doing the same what I am in that code sample above when it is at the end of line.

Yes. The idea is that you would not need to have font specific code. `rtbd`/`lfbd` are general features, and if a font has them you can apply them and get the required effect, and if the font does not, then you assume it does not require this treatment.

> I have been trying to avoid mutating the input string (as that would require a lot of either copying or pointer bookkeeping).

I’m not suggesting you mutate the input string during rendering, but simply using a different text when using Raqq. This is required anyway, since replicating Kufic manuscripts will always require different input text as the standard Quranic text has much more marks and small letters than Kufic manuscripts.


> > Also, to identify what character a glyph belongs on, you use info.cluster, it is an index into input string (it is a bit tricky to use, though, because of combining marks, decomposition, ligature, check HarfBuzz user manual on how to use it).
> 
> Yeah I understand the cluster marker. I am not sure what this is in reference to.

Your code snippet has hardcoded glyph ids for ayah and space, so I thought you might want a more robust and standarad way to identify them.

> I worked on it a bit yesterday and managed to make it work for the other end of ayah markers.
> 
> ![ikhlas_50](https://private-user-images.githubusercontent.com/17417266/326177970-dc63f623-b22d-4cc1-974b-c264065bf540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDcxMzgsIm5iZiI6MTcxNTUwNjgzOCwicGF0aCI6Ii8xNzQxNzI2Ni8zMjYxNzc5NzAtZGM2M2Y2MjMtYjIyZC00Y2MxLTk3NGItYzI2NDA2NWJmNTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA5NDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYzI5NzMxN2I1MDI4ZGNlYWYyNzBkNDE2NWQzNWYzYzk3ZTdmMGUxODIzOTczMzhjNmU1MWNjMjY0YjI1ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ML0aJwjHN_ZcPs7isxNvlIy1EYq-2J2L2CexzARTt8)

This looks good, but it also shows why using the bounds features and special input might be better. Namely, the 10s ayah symbols need wider space since they are larger than regular one, but in the image they are overlapping the text.

> I am going to try adding this to the font via the wasm shaper. I don't know how to make it feature gated tho. (and which feature? ss02?)

I’m not sure what do you want added to the font.
